### PR TITLE
Updated version

### PR DESCRIPTION
**Pull request by m157y**
@mkleehammer, please release last changes as new version, because it'll be more comfortable to search and install it via npmjs.com instead of private repo.

### CODE REVIEW

**Comment by m157y** [comment]
ping @mkleehammer

**Comment by mkleehammer** [comment]
Sorry - when I published I think I confused the commands with Atom's apm publish which automatically bumps the version number, adds a tag, and pushes the repository.  (Which would be a great npm addition.)

**Comment by mkleehammer** [comment]
I apologize - I thought I had taken care of this and was then on vacation for a few days.  Instead of merging I wanted to walk through the workflow again:

1. npm version minor
2. npm publish

**Comment by m157y** [comment]
@mkleehammer  Thank you very match

**Pull request closed without merging**
